extends:
  - './.eslint/react-a11y.yml'
  - 'prettier'
  - 'prettier/react'
parser: babel-eslint
plugins:
  - prettier
rules:
  no-confusing-arrow:
    - error
    - allowParens: true
  prettier/prettier: error