language: node_js
node_js:
  - "7"
cache:
  yarn: true
  directories:
    - node_modules
script: yarn test:ci

# Greenkeeper
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload