job_defaults: &job_defaults
  docker:
    - image: circleci/node:8.3.0
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: node_modules
          paths:
            - .

  lint:
    <<: *job_defaults

    steps:
      - attach_workspace:
          at: node_modules
      
      - run:
          name: Lint
          command: yarn lint

  test_coverage:
    <<: *job_defaults

    steps:
      - attach_workspace:
          at: node_modules
      
    #   - run:
    #       name: Before tests
    #       command: ./node_modules/.bin/greenkeeper-lockfile-update
      - run:
          name: Run tests
          command: yarn test:coverage
    #   - run:
    #       name: After tests
    #       command: ./node_modules/.bin/greenkeeper-lockfile-upload

  deploy:
    <<: *job_defaults

    steps:
      - attach_workspace:
          at: node_modules
      
      - run: echo "Deploy here, eventually"
        
workflows:
  version: 2
  build_lint_test_coverage_deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test_coverage:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - test_coverage
